# Generated by Django 3.2.19 on 2023-08-10 09:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowCount', models.IntegerField()),
                ('operationId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rowCount', models.IntegerField()),
                ('operationId', models.IntegerField()),
                ('personId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='users.person')),
            ],
        ),
        migrations.CreateModel(
            name='StudyField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(max_length=255)),
                ('backkOfficeName', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateField()),
                ('startReason', models.IntegerField()),
                ('obligatorySchoolAttendenceYears', models.IntegerField()),
                ('endDate', models.DateField(blank=True, null=True)),
                ('endReason', models.IntegerField(blank=True, null=True)),
                ('focus', models.CharField(max_length=255)),
                ('formAttendence', models.IntegerField()),
                ('formOfEducation', models.IntegerField()),
                ('financing', models.IntegerField()),
                ('individualPlanId', models.IntegerField(blank=True, null=True)),
                ('validSince', models.DateField()),
                ('validTo', models.DateField(blank=True, null=True)),
                ('StudentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentDetailStudent', to='scholl_class.student')),
                ('classId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentDetailClass', to='scholl_class.class')),
                ('organizationID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentDetailOperation', to='organizations.organization')),
                ('studyFieldId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentDetailStudyField', to='scholl_class.studyfield')),
                ('virtualOperationId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studentDetailVirtualOperation', to='organizations.virtualoperation')),
            ],
        ),
    ]
