# Generated by Django 3.2.19 on 2023-08-24 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl_class', '0002_auto_20230824_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='obligatorySchoolAttendenceYears',
            field=models.CharField(choices=[('A', 'Přijetí do 1.ročníku'), ('B', 'Přijetí do 3.ročníku 6letého gymnázia'), ('C', 'Přijetí do 5.ročníku 8letého gymnázia'), ('D', 'Přijetí do vyššího ročníku (podle § 63 resp. § 95 ŠZ)'), ('E', 'Přestup z jiné školy (podle § 66 odst.4 resp.§ 95 odst.5 ŠZ)'), ('F', 'Přestup z nižšího stupně víceletého gymnázia do 4letého oboru gymnázia'), ('H', 'Převedení z jiné školy (zánik, sloučení škol)')], max_length=1),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='startReason',
            field=models.CharField(choices=[('A', 'Přijetí do 1.ročníku'), ('B', 'Přijetí do 3.ročníku 6letého gymnázia'), ('C', 'Přijetí do 5.ročníku 8letého gymnázia'), ('D', 'Přijetí do vyššího ročníku (podle § 63 resp. § 95 ŠZ)'), ('E', 'Přestup z jiné školy (podle § 66 odst.4 resp.§ 95 odst.5 ŠZ)'), ('F', 'Přestup z nižšího stupně víceletého gymnázia do 4letého oboru gymnázia'), ('H', 'Převedení z jiné školy (zánik, sloučení škol)')], max_length=1),
        ),
    ]
