# Generated by Django 3.2.19 on 2023-09-02 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl_class', '0005_auto_20230902_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='methodOfSchoolAttendance',
            field=models.IntegerField(choices=[(11, 'Školní docházka ve škole zapsané ve školském rejstříku'), (15, 'Plnění PŠD podle § 50 odst. 3 ŠZ'), (21, 'Plnění PŠD podle § 38 odst. 1, písm. a) ŠZ'), (22, 'Plnění PŠD podle § 38 odst. 1, písm. b) ŠZ'), (23, 'Plnění PŠD podle § 38 odst. 1, písm. c) ŠZ'), (24, 'Individuální výuka v zahraničí podle § 38 odst. 2 ŠZ'), (25, 'Plnění PŠD podle § 38 odst. 1, písm. d) ŠZ v tzv. "evropské škole"'), (30, 'Individuální vzdělávání podle § 41 ŠZ'), (40, 'Plnění PŠD podle § 42 ŠZ')], default=11),
        ),
    ]
