# Generated by Django 3.2.19 on 2023-09-07 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciselniky', '0002_alter_st_skoly_id'),
        ('scholl_class', '0007_auto_20230903_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ciselniky.rocnik'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='yearsOfStudy',
            field=models.CharField(default='9', max_length=255),
        ),
    ]
