# Generated by Django 3.2.19 on 2023-09-07 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciselniky', '0003_delete_let_psd'),
        ('scholl_class', '0008_auto_20230907_1327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='grade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='ciselniky.rocnik'),
        ),
    ]
