# Generated by Django 3.2.19 on 2023-09-11 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciselniky', '0003_delete_let_psd'),
        ('scholl_class', '0011_alter_studentdetail_interruption'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='endReason',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentDetailKOD_UKON', to='ciselniky.kod_ukon'),
        ),
    ]
