# Generated by Django 3.2.19 on 2023-09-14 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciselniky', '0003_delete_let_psd'),
        ('scholl_class', '0012_alter_studentdetail_endreason'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='codeSentence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentDetailKOD_VETY', to='ciselniky.kod_vety'),
        ),
        migrations.AlterField(
            model_name='studentdetail',
            name='codeChange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='studentDetailKOD_ZMEN', to='ciselniky.kod_zmen'),
        ),
    ]
