# Generated by Django 3.2.19 on 2023-09-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl_class', '0013_auto_20230914_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetail',
            name='focus',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
