# Generated by Django 3.2.19 on 2023-09-27 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scholl_class', '0014_alter_studentdetail_focus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetail',
            name='zmen_dat',
            field=models.DateField(blank=True, null=True),
        ),
    ]
