from django.contrib import admin
from .models import *
# Register your models here.

admin.site.register(OBECB)
admin.site.register(Sex)
admin.site.register(InsuranceCompany)
admin.site.register(KSTPR)
admin.site.register(STPR)
admin.site.register(OKRESB)
admin.site.register(ODHL)
admin.site.register(STUPEN)
admin.site.register(KOD_ZAH)
admin.site.register(KOD_UKON)
admin.site.register(ROCNIK)
admin.site.register(PRIZN_ST)
admin.site.register(ZPUSOB)
admin.site.register(DRST)
admin.site.register(DELST)
admin.site.register(OBOR)
admin.site.register(OBOR2)
admin.site.register(FST)
admin.site.register(ForeignLanguage)
admin.site.register(FieldLanguage)
admin.site.register(FIN)
admin.site.register(KOD_ZMEN)
admin.site.register(KOD_VETY)
admin.site.register(ST_SKOLY)
admin.site.register(P_JAZ)
admin.site.register(KOD_ZK)
admin.site.register(ExamType)
admin.site.register(Success)
admin.site.register(PRERUS)
