apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: parami-group
  name: postgres-pvc
  labels:
    type: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  volumeName: postgres-pv
