# Generated by Django 3.2.19 on 2023-08-24 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='personTypeId',
            field=models.IntegerField(choices=[(1, 'Student'), (2, 'Teacher'), (3, 'Employee')]),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='familyStatus',
            field=models.IntegerField(blank=True, choices=[(1, 'Single')], null=True),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='inactiveReasonId',
            field=models.IntegerField(blank=True, choices=[(1, 'Úspěšné absolvování'), (2, 'Ukončení vzdělávacího programu bez předepsané zkoušky'), (3, 'Přestup na jinou školu'), (4, 'Nepostoupení do vyššího ročníku, nesplnění podmínek pro konání zkoušky'), (5, 'Zanechání vzdělávání'), (6, 'Vyloučení'), (8, 'Úmrtí'), ('G', 'Ukončení pro cizince (odstěhování)'), ('H', 'Převední do jiné školy (sloučení škol, splynutí, změna IZO)')], null=True),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='insuranceCompany',
            field=models.IntegerField(blank=True, choices=[(111, 'Všeobecná zdravotní pojišťovna České republiky'), (201, 'Vojenská zdravotní pojišťovna České republiky'), (205, 'Česká průmyslová zdravotní pojišťovna'), (207, 'Oborová zdravotní pojišťovna zaměstnanců bank, pojišťoven a stavebnictví'), (209, 'Zaměstnanecká pojišťovna Škoda'), (211, 'Zdravotní pojišťovna ministerstva vnitra České republiky'), (213, 'RBP, zdravotní pojišťovna')], null=True),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='sex',
            field=models.CharField(choices=[(1, 'Male'), (2, 'Female')], max_length=10),
        ),
    ]
