# Generated by Django 3.2.19 on 2023-09-03 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ciselniky', '0001_initial'),
        ('users', '0006_persondetail_previousschoolcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adressOBECB', to='ciselniky.obecb'),
        ),
        migrations.AlterField(
            model_name='address',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adressOKRESB', to='ciselniky.okresb'),
        ),
        migrations.AlterField(
            model_name='address',
            name='stateDistrict',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='citizenship',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personDetailSTPR', to='ciselniky.stpr'),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='citizenshipCode',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personDetailKSTPR', to='ciselniky.kstpr'),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='education',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personDetailSTUPEN', to='ciselniky.stupen'),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='inactiveReasonId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personDetailKOD_UKON', to='ciselniky.kod_ukon'),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='insuranceCompany',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personDetailInsuranceCompany', to='ciselniky.insurancecompany'),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='previousSchool',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personDetailODHL', to='ciselniky.odhl'),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='sex',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personDetailSex', to='ciselniky.sex'),
        ),
    ]
