# Generated by Django 3.2.19 on 2023-09-07 11:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20230903_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetail',
            name='inactiveReasonId',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(24), django.core.validators.MinValueValidator(0)]),
        ),
    ]
