# Generated by Django 3.2.19 on 2023-09-27 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_persondetail_inactivereasonid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetail',
            name='identityCardNumber',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
