# Generated by Django 3.2.19 on 2023-09-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_persondetail_identitycardnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetail',
            name='identificationCode',
            field=models.CharField(help_text='Bez lomítka(/)', max_length=11),
        ),
        migrations.AlterField(
            model_name='persondetail',
            name='identityCardNumber',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
