# Generated by Django 3.2.19 on 2023-10-02 10:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20230927_1607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persondetail',
            name='birthAddressId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personDetailBirth', to='users.address'),
        ),
    ]
