# Generated by Django 3.2.19 on 2023-09-03 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ciselniky', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='st_skoly',
            name='id',
            field=models.CharField(max_length=8, primary_key=True, serialize=False, unique=True),
        ),
    ]
