# Generated by Django 3.2.19 on 2023-09-07 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scholl_class', '0008_auto_20230907_1327'),
        ('ciselniky', '0002_alter_st_skoly_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LET_PSD',
        ),
    ]
