# Generated by Django 3.2.19 on 2023-08-10 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataOperationId', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cin', models.CharField(max_length=9, unique=True)),
                ('icoAuthority', models.IntegerField()),
                ('osszName', models.CharField(max_length=255)),
                ('osszDistrictId', models.IntegerField()),
                ('osszVariableSymbol', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('uniqueCode', models.CharField(max_length=255)),
                ('website', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueCode', models.CharField(max_length=255)),
                ('codeTypeId', models.IntegerField()),
            ],
        ),
    ]
