# Generated by Django 3.2.19 on 2023-08-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_alter_organization_osszdistrictid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='osszDistrictId',
            field=models.IntegerField(choices=[('1', 'Praha 1'), ('2', 'Praha 2')]),
        ),
    ]
