# Generated by Django 3.2.19 on 2023-08-10 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_organization_osszdistrictid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='osszDistrictId',
            field=models.IntegerField(choices=[(1, 'Praha 1'), (2, 'Praha 2')]),
        ),
        migrations.AlterField(
            model_name='virtualoperation',
            name='codeTypeId',
            field=models.IntegerField(choices=[(1, 'IZO'), (2, 'IZO')]),
        ),
    ]
